### PR TITLE
The use of #pragma once is nonstandard

### PR DESCRIPTION
**Pull request by davidfetter**
Replace same with #ifndef/#defined/#endif, which is standard.

You're free to use this just as you like :)

### CODE REVIEW

**Comment by AmatanHead** [comment]
Thanks! Never seen uuid4 used as include guard. Interesting =)

**Comment by davidfetter** [comment]
I'm just starting to learn C, but I got a hint from @RhodiumToad both about `#pragma once` about alternatives.

**Comment by RhodiumToad** [comment]
You shouldn't really use a leading underscore there. A reasonable style might be to use H_uuid or something similar.

**Comment by AmatanHead** [comment]
@RhodiumToad hmm yes, it violates the standard, though it's unlikely to collide with anything from the standard library.

Anyway, thinking about it once again, I don't really see how `#pragma once` could be an issue. I mean, yes, it's non-standard, but it's supported by fairly all of the compilers out there (given that there's [CMAKE_C_STANDARD 11](https://github.com/AmatanHead/antlr4/blob/master/runtime/C/CMakeLists.txt#L18), it's unlikely that someone would use this runtime with a compiler that doesn't support it).

So compared to use of `uint64_t` and [designated initializers](https://github.com/AmatanHead/antlr4/blob/master/runtime/C/antlr4/memory/pool.h#L41), this seems to be the least of portability problems.

As a bonus, with `#pragma once`, there are almost no ways for things to go wrong, while with include guards and the requirement to generate a uuid4 for each file, there are plenty.

**Comment by RhodiumToad** [comment]
Feel free to ignore me since I have no involvement in your project, I just happen to have mentioned the issue to @davidfetter in the context of another project.

I recently decided to research whether to switch some of my own code to using pragma once, and decided not to. The main advantages of pragma once: not introducing a useless macro name, not getting into problems with duplicate names. The main disadvantage: can't cope with cases where a single file is copied or linked from multiple places. My conclusion was that using conventional include guards with UUIDs (rather than filenames which run into collision problems in large projects) solved the duplication problems better than pragma once did, and at least the macro namespace for include guards can be confined to some single prefix to keep them out of the way of real definitions. Your mileage may vary of course.

**Pull request merged**
